[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.19"
# Reason for why this flag is required can be found here: https://github.com/foundry-rs/foundry/issues/7607
unchecked_cheatcode_artifacts = true
# Reasons for why this flag is required can be found here: https://book.getfoundry.sh/cheatcodes/expect-revert#description
allow_internal_expect_revert = true